# Generated by Django 3.1 on 2021-04-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('syllabus', models.FileField(blank=True, max_length=500, null=True, upload_to='syllabus/')),
            ],
        ),
    ]
