# Generated by Django 3.1 on 2021-04-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content_files',
            field=models.FileField(max_length=500, upload_to='lectures/uploads/'),
        ),
    ]
