# Generated by Django 3.1 on 2021-04-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_auto_20210421_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content_files',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='lectures/uploads/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
